server:
  port: 9007

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: ACCOUNT-SERVICE
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/accounts/**
        - id: ADDRESS-SERVICE
          uri: lb://ADDRESS-SERVICE
          predicates:
              - Path=/addresses/**
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
              - Path=/payments/**
        - id: TRANSACTION-SERVICE
          uri: lb://TRANSACTION-SERVICE
          predicates:
              - Path=/transactions/**
        - id: UTILITY-ACCOUNT-SERVICE
          uri: lb://UTILITY-ACCOUNT-SERVICE
          predicates:
              - Path=/utilities/**
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
              - Path=/customers/**





eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    hostname: localhost